[package]
name = "cvm-rs"
description = "Rust utility library for cvmts. Runs all the high performance code"
version = "0.2.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.155"

# Required for JPEG
once_cell = "1.19.0"
turbojpeg-sys = "1.0.0"
rayon = "1.10.0"

# node sex
napi =  { version = "2.16.9", features = [ "async", "napi8", "error_anyhow" ] }
napi-derive = "2.16.11"
anyhow = "1.0.86"

# vnc
vnc-rs = { git = "https://github.com/computernewb/vnc-rs.git" }
tokio = { version = "1.39.3", features = ["full"] }

[build-dependencies]
napi-build = "2.1.3"
